apiVersion: v1
kind: Service
metadata:
  name: s3-presigned-api-service
  namespace: s3-presigned-api
  labels:
    app: s3-presigned-api
spec:
  selector:
    app: s3-presigned-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: ClusterIP